logpath: test.log
rules:
  - name: Open block rule
    syscall: openat
    action: Warn

  - name: Close block rule
    syscall: close
    action: Log

  - name: Exit group block rule
    syscall: exit_group
    action: Block
